# Generated by Django 5.1.1 on 2024-09-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='demo',
            new_name='demo_url',
        ),
    ]
