# Generated by Django 5.1.1 on 2024-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloads',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
