# Generated by Django 5.1.1 on 2024-09-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_usd_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='usd_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
