# Generated by Django 5.1.1 on 2024-09-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_usd_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
