# Generated by Django 5.1.1 on 2024-09-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_vendor_mobile_vendor_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
